// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';

export const environment = {
  production: false,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
};



